Add tests for omniscidb-internal PR 5403
xnd-project/rbc pull request #313
Opened 2021-03-24 04:08 UTC by guilhermeleobas

As title. Requires PR https://github.com/omnisci/omniscidb-internal/pull/5403

2021-04-01 17:42 UTC, guilhermeleobas commented
dev build is failing because the omniscidb server (5, 7) is equals to the version I'm using in one of the tests. I think it is safe to assume that once omnisci/omniscidb-internal#5403 gets merged and the dev container gets updated, this tests will pass.

2021-04-02 12:55 UTC, pearu commented
@guilhermeleobas to handle the out-of-date omniscidb docker failures, you can now (after rebasing) specify the expected date of omniscidb dev version to skip tests using the future features. See the `date` argument in
https://github.com/xnd-project/rbc/blob/e105e1a292e3901f1c4513ade52c5354079c6c19/rbc/tests/test_omnisci_udtf.py#L66
as an example.

2021-04-06 17:31 UTC, guilhermeleobas commented
Failures are not related to changes but with an HTTP error in conda

2021-04-29 13:24 UTC, pearu requested changes
Mostly nits. The regression introduced by https://github.com/omnisci/omniscidb-internal/pull/5403 is worrying.

Also, in the future, we should avoid modifying tests that are maintained under omniscidb repository unless the test are made version dependent explicitly. For instance, running the tests of this PR using the master omniscidb will lead to test failures.

2021-04-29 13:24 UTC, pearu commented on rbc/tests/test_omnisci_column_basic.py
> +    pytest.xfail('Test failing due to the introduction of default sizer. See PR 313')
The test passes when using omniscidb master. So, the regression is introduced in https://github.com/omnisci/omniscidb-internal/pull/5403

2021-05-15 17:17 UTC, merged

2021-05-15 17:18 UTC, pearu commented
Merged because it was blocking in testing the master of omniscidb-internal.

The nits need to be resolved in subsequent PRs.

2021-05-16 23:12 UTC, guilhermeleobas commented on rbc/tests/test_omnisci_column_basic.py
> +    pytest.xfail('Test failing due to the introduction of default sizer. See PR 313')
> The test passes when using omniscidb master. So, the regression is introduced in omnisci/omniscidb-internal#5403

Not really. The regression was already there, we just didn't have a test covering it. https://github.com/xnd-project/rbc/issues/319 contains a reproducer for this error.