Tests for MLPack support: db_scan, kmeans
xnd-project/rbc pull request #317
Opened 2021-04-02 13:55 UTC by pearu

Requires https://github.com/omnisci/omniscidb-internal/pull/5430

2021-04-06 18:51 UTC, guilhermeleobas commented
I got the following output when using pytest:

```bash
~/git/rbc:pearu/mlpack-tests (rbc-dev) guilhermel@qgpu3 $ pytest rbc/tests/test_omnisci_mlpack.py -rs -sv
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /home/guilhermel/.conda/envs/rbc-dev/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/guilhermel/git/rbc/.hypothesis/examples')
rootdir: /home/guilhermel/git/rbc, configfile: setup.cfg
plugins: hypothesis-6.4.0
collected 2 items

rbc/tests/test_omnisci_mlpack.py::test_mlpack[db_scan]  OmnisciDB version (5, 7, 0, 'dev-20210406-dd992f39d9')
SKIPPED (test requires omniscidb server with MLPACK support: SQL Error: From line 2, column 12 to line 3, column 53: No match found for function signature db_scan(<CU...)
rbc/tests/test_omnisci_mlpack.py::test_mlpack[kmeans] PASSED

======================================================================================================== short test summary info ========================================================================================================
SKIPPED [1] rbc/tests/test_omnisci_mlpack.py:32: test requires omniscidb server with MLPACK support: SQL Error: From line 2, column 12 to line 3, column 53: No match found for function signature db_scan(<CURSOR>, <NUMERIC>, <NUMERIC>, <NUMERIC>)
===================================================================================================== 1 passed, 1 skipped in 0.96s ======================================================================================================
```

Is this the expected output?

2021-04-06 19:19 UTC, pearu commented
> I got the following output when using pytest:
...
> Is this the expected output? `kmeans` worked just fine but `db_scan` query failed.

If omniscidb is built with mlpack support, then no.

2021-04-06 23:30 UTC, guilhermeleobas requested changes
LGMT! Just a minor change

2021-04-06 23:30 UTC, guilhermeleobas commented on rbc/tests/test_omnisci_mlpack.py
> +@pytest.mark.parametrize("func", ['db_scan', 'kmeans'])
The name is actually `dbscan`, without the underscore.

```suggestion
@pytest.mark.parametrize("func", ['dbscan', 'kmeans'])
```

2021-04-06 23:30 UTC, guilhermeleobas commented on rbc/tests/test_omnisci_mlpack.py
> +    extra_args = dict(db_scan='cast(1 as float), 1',
```suggestion
    extra_args = dict(dbscan='cast(1 as float), 1',
```

2021-04-06 23:30 UTC, guilhermeleobas commented on rbc/tests/test_omnisci_mlpack.py
> +        db_scan=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)],
```suggestion
        dbscan=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)],
```

2021-04-07 06:00 UTC, guilhermeleobas commented
Also, do you think it is a good idea for RBC to know if the server has support for armadillo/mlpack?

2021-04-07 19:44 UTC, merged