Tests for Numba 0.54.0 RC3
xnd-project/rbc pull request #353
Opened 2021-08-12 04:16 UTC by guilhermeleobas

2021-08-17 10:06 UTC, pearu requested changes
Thanks, @guilhermeleobas for adding numba 0.54 support!

I have a couple of code quality suggestions such as introducing numba version dependent hooks into irtools.py so that other parts of the code would not need to deal with numba version checks.

2021-08-17 10:06 UTC, pearu commented on rbc/externals/stdio.py
> +        fflush_fn = builder.module.get_or_insert_function(fflush_fnty, name="fflush")
Use:
```
fflush_fn = irtools.get_or_insert_function(builder.module, fflush_fnty, name='fflush')
```
(see below)

2021-08-17 16:03 UTC, guilhermeleobas commented on rbc/structure_type.py
> +        raise ValueError(struct.opname)
`index` is a scalar value, thus, `builder.extract_value(struct, [index])` is the correct to build the instruction

2021-08-17 16:05 UTC, guilhermeleobas commented on .conda/environment.yml
> +  - numba
Sure! I guess the `numba` channel is only need for this candidate release. After that, we can remove it.

2021-08-17 16:54 UTC, pearu commented on rbc/structure_type.py
> +        raise ValueError(struct.opname)
Is `extract_value` path used only when using `numba>=0.54`? If so, and considering the usage of `irutils.get_member_value` elsewhere, the code here does not follow the same pattern. I wonder if this indicates a bug or did we have the code wrong for `numba<0.54`?

2021-08-17 20:09 UTC, guilhermeleobas commented on rbc/structure_type.py
> +        raise ValueError(struct.opname)
I guess they're equivalent. The current approach only emit a few more instructions but the tests pass with
```python
@lowering_registry.lower_getattr_generic(StructureNumbaType)
def StructureNumbaType_getattr_impl(context, builder, sig, struct, attr):
    model = datamodel.default_manager.lookup(sig)
    index = model.get_field_position(attr)
    return get_member_value(builder, struct, index)
```

2021-08-22 19:58 UTC, pearu approved these changes
LGTM!

I have rebased the PR with the current master and disabled some tests that require https://github.com/omnisci/omniscidb-internal/pull/5809 when using cuda-enabled omniscidb server.

The PR can be merged when CI is green.

2021-08-22 20:23 UTC, merged