Drop support for omniscidb v5.(2/3/4/5)
xnd-project/rbc pull request #386
Opened 2021-12-01 16:54 UTC by guilhermeleobas

As title

2021-12-01 18:23 UTC, pearu requested changes
See my comment below. We should ensure that rbc failure from connection to unsupported omniscidb server version is user-friendly and informative: the failure is not due to a bug but unsupported omniscidb version.

2021-12-01 18:23 UTC, pearu commented on rbc/omniscidb.py
> -        use_sql = self.version[:2] < (5, 3)
When a given rbc version connects to some older omniscidb version, something will break below. In order to notify that the breakage is not a bug, let's have here at least the following assert statement:
```python
        assert self.version[:2] >= (5, 6), self.version  # omniscidb is too old
```

The above note applies to all changes in this PR that may cause rbc failure when connecting to an unsupported omniscidb version.

2021-12-02 17:31 UTC, guilhermeleobas commented
Pearu, I've replaced the exception by a pending deprecation warning. This way, we will not break any existing code using older versions of omniscidb

2021-12-05 21:14 UTC, pearu approved these changes
I have a minor nit but LGTM! Thanks, @guilhermeleobas!

2021-12-05 21:14 UTC, pearu commented on rbc/omniscidb.py
> +                msg = (f'OmniSciDB server is too old (v.{ver}) and some '
Nit:
```suggestion
                msg = (f'OmniSciDB server v.{version} is too old (expected v.5.6 or newer) and some '
```

2021-12-06 20:07 UTC, merged