ENH: add support for list to execute
xnd-project/rbc pull request #430
Opened 2022-02-08 22:08 UTC by tupui

Add support for passing `list` to a parameter of type array in `RemoteOmnisci.execute`. This is handy for debugging.

```python
@omnisci('double(double[])')
def fahrenheit2celsius(f):
    return (mean(f)-32) * 5 / 9

fahrenheit2celsius([1, 2, 3]).execute()
```

2022-02-11 18:06 UTC, guilhermeleobas commented
I get a `NotImplementedError` from the Typesystem with your example

```python
=================================================================================================== FAILURES ====================================================================================================____________________________________________________________________________________________________ test_fx ____________________________________________________________________________________________________
omnisci = <rbc.omniscidb.RemoteOmnisci object at 0x7f1a8d8747f0>

    def test_fx(omnisci):
        from rbc.omnisci_backend import mean

        @omnisci('double(double[])')
        def fahrenheit2celsius(f):
            return (mean(f)-32) * 5 / 9

>       fahrenheit2celsius([1, 2, 3]).execute()

rbc/tests/test_omnisci_caller.py:237:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _rbc/remotejit.py:381: in __call__
    return caller(*arguments, device=device, hold=hold)
rbc/remotejit.py:416: in __call__
    atypes = self.remotejit.get_types(*arguments)
rbc/omniscidb.py:1332: in get_types
    types.append(typesystem.Type.fromvalue(value))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cls = <class 'rbc.typesystem.Type'>, obj = [1, 2, 3]

    @classmethod
    def fromvalue(cls, obj):
        """Return Type instance that corresponds to given value.
        """
        for mapping in [_python_imap, _numpy_imap]:
            n = mapping.get(type(obj))
            if n is not None:
                return cls.fromstring(n)
        if isinstance(obj, _ctypes._Pointer):
            return cls.fromctypes(obj._type_).pointer()
        if isinstance(obj, ctypes.c_void_p):
            return cls(cls(), '*')
        if hasattr(obj, '__typesystem_type__'):
            return cls.fromobject(obj.__typesystem_type__)

>       raise NotImplementedError('%s.fromvalue(%r|%s)'
                                  % (cls.__name__, obj, type(obj)))
E       NotImplementedError: Type.fromvalue([1, 2, 3]|<class 'list'>)
```

2022-02-11 18:12 UTC, tupui commented
> I get a `NotImplementedError` from the Typesystem with your example
> 
> ```python
> =================================================================================================== FAILURES ====================================================================================================____________________________________________________________________________________________________ test_fx ____________________________________________________________________________________________________
> omnisci = <rbc.omniscidb.RemoteOmnisci object at 0x7f1a8d8747f0>
> 
>     def test_fx(omnisci):
>         from rbc.omnisci_backend import mean
> 
>         @omnisci('double(double[])')
>         def fahrenheit2celsius(f):
>             return (mean(f)-32) * 5 / 9
> 
> >       fahrenheit2celsius([1, 2, 3]).execute()
> 
> rbc/tests/test_omnisci_caller.py:237:
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _rbc/remotejit.py:381: in __call__
>     return caller(*arguments, device=device, hold=hold)
> rbc/remotejit.py:416: in __call__
>     atypes = self.remotejit.get_types(*arguments)
> rbc/omniscidb.py:1332: in get_types
>     types.append(typesystem.Type.fromvalue(value))
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> cls = <class 'rbc.typesystem.Type'>, obj = [1, 2, 3]
> 
>     @classmethod
>     def fromvalue(cls, obj):
>         """Return Type instance that corresponds to given value.
>         """
>         for mapping in [_python_imap, _numpy_imap]:
>             n = mapping.get(type(obj))
>             if n is not None:
>                 return cls.fromstring(n)
>         if isinstance(obj, _ctypes._Pointer):
>             return cls.fromctypes(obj._type_).pointer()
>         if isinstance(obj, ctypes.c_void_p):
>             return cls(cls(), '*')
>         if hasattr(obj, '__typesystem_type__'):
>             return cls.fromobject(obj.__typesystem_type__)
> 
> >       raise NotImplementedError('%s.fromvalue(%r|%s)'
>                                   % (cls.__name__, obj, type(obj)))
> E       NotImplementedError: Type.fromvalue([1, 2, 3]|<class 'list'>)
> ```

@guilhermeleobas yes that's exactly my issue. I thought it should be enough to do it on `RemoteOmnisci`. While debugging, I can see that my new code is getting executed so I am missing something.

2022-02-12 11:48 UTC, tupui commented
> The suggestion should resolve the example failure.

Oh thanks! I knew it must must be something simple. I can focus on the logic now.

2022-02-17 13:49 UTC, pearu requested changes
@tupui I have fixed https://github.com/xnd-project/rbc/pull/430#issuecomment-1041707693 in my last commit.

I think the PR is functional but it requires a rewrite in `fromtypes` functionality as described in the comment.

2022-02-17 15:23 UTC, tupui commented
Locally `intxx` is crashing the server without message.

Also, following NumPy's [doc](https://numpy.org/doc/stable/user/basics.types.html#overflow-errors), I added a fix for when we have `int16` and above and `float16`. There is no further issue with `float32` as it's large enough.
```python
np.finfo(np.float16)
# finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
np.finfo(np.float32)
# finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
np.iinfo(np.int16)
# iinfo(min=-32768, max=32767, dtype=int16)
np.iinfo(np.int32)
# iinfo(min=-2147483648, max=2147483647, dtype=int32)
```

2022-02-17 15:49 UTC, tupui commented
Crash is fixed locally. I needed to add `omnisci.unregister()`.

2022-02-18 21:14 UTC, guilhermeleobas commented
@tupui, I wonder if the crash is related to LLVM generating the wrong body for the function. Can you dump the llvm IR of the function on the server before the `.execute()` call? You can dump the IR by calling the method `.describe()`

2022-02-19 16:20 UTC, pearu commented on rbc/tests/test_omnisci.py
> +    def farhenheit2celcius(f):
To resolve CI failures, try also renaming `farhenheit2celcius`, say, to `farhenheit2celcius_arr`.

2022-02-21 09:40 UTC, tupui commented
> @tupui, I wonder if the crash is related to LLVM generating the wrong body for the function. Can you dump the llvm IR of the function on the server before the `.execute()` call? You can dump the IR by calling the method `.describe()`

@guilhermeleobas here is the output.


<details>
<summary>IR</summary>

```python
--------------------------------------cpu---------------------------------------
; ModuleID = 'rbc.irtools.compile_to_IR'
source_filename = "<string>"
target triple = "x86_64-unknown-linux-gnu"
@_ZN08NumbaEnv3rbc5tests12test_omnisci22test_direct_call_array12_3clocals_3e27farhenheit2celcius_arr_2421B40c8tJTC_2fWQA9HW1CcAv0EjzIkAdRoAEtoAgA_3dE63BufferPointer_5bSTRUCT__fPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend11numpy_funcs18omnisci_array_mean12_3clocals_3e9impl_2422B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__fPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend14omnisci_buffer18omnisci_buffer_len12_3clocals_3e16_3clambda_3e_243B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__fPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend11numpy_funcs14omnisci_np_sum12_3clocals_3e8impl_244B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__fPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a27omitted_28default_3dNone_29 = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend14omnisci_buffer22omnisci_buffer_getitem12_3clocals_3e16_3clambda_3e_245B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__fPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2ax = common local_unnamed_addr global i8* null
@printf_format = internal constant [20 x i8] c"Mean of empty array\00"
@_ZN08NumbaEnv3rbc5tests12test_omnisci22test_direct_call_array12_3clocals_3e27farhenheit2celcius_arr_2423B40c8tJTC_2fWQA9HW1CcAv0EjzIkAdRoAEtoAgA_3dE63BufferPointer_5bSTRUCT__dPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend11numpy_funcs18omnisci_array_mean12_3clocals_3e9impl_2424B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__dPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend14omnisci_buffer18omnisci_buffer_len12_3clocals_3e16_3clambda_3e_248B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__dPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend11numpy_funcs14omnisci_np_sum12_3clocals_3e8impl_249B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__dPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a27omitted_28default_3dNone_29 = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend14omnisci_buffer22omnisci_buffer_getitem12_3clocals_3e17_3clambda_3e_2410B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__dPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2ax = common local_unnamed_addr global i8* null
@printf_format.5 = internal constant [20 x i8] c"Mean of empty array\00"
@_ZN08NumbaEnv3rbc5tests12test_omnisci22test_direct_call_array12_3clocals_3e27farhenheit2celcius_arr_2425B40c8tJTC_2fWQA9HW1CcAv0EjzIkAdRoAEtoAgA_3dE63BufferPointer_5bSTRUCT__lPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend11numpy_funcs18omnisci_array_mean12_3clocals_3e9impl_2426B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__lPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend14omnisci_buffer18omnisci_buffer_len12_3clocals_3e17_3clambda_3e_2413B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__lPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend11numpy_funcs14omnisci_np_sum12_3clocals_3e9impl_2414B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__lPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a27omitted_28default_3dNone_29 = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend14omnisci_buffer22omnisci_buffer_getitem12_3clocals_3e17_3clambda_3e_2415B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__lPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2ax = common local_unnamed_addr global i8* null
@printf_format.8 = internal constant [20 x i8] c"Mean of empty array\00"
@_ZN08NumbaEnv3rbc5tests12test_omnisci22test_direct_call_array12_3clocals_3e27farhenheit2celcius_arr_2427B40c8tJTC_2fWQA9HW1CcAv0EjzIkAdRoAEtoAgA_3dE63BufferPointer_5bSTRUCT__iPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend11numpy_funcs18omnisci_array_mean12_3clocals_3e9impl_2428B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__iPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend14omnisci_buffer18omnisci_buffer_len12_3clocals_3e17_3clambda_3e_2418B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__iPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend11numpy_funcs14omnisci_np_sum12_3clocals_3e9impl_2419B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__iPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a27omitted_28default_3dNone_29 = common local_unnamed_addr global i8* null
@_ZN08NumbaEnv3rbc15omnisci_backend14omnisci_buffer22omnisci_buffer_getitem12_3clocals_3e17_3clambda_3e_2420B40c8tJTIeFCjyCbUFRqqOAK_2f6h0phxApbQBAA_3dE63BufferPointer_5bSTRUCT__iPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2ax = common local_unnamed_addr global i8* null
@printf_format.11 = internal constant [20 x i8] c"Mean of empty array\00"
; Function Attrs: nofree nounwind
define float @farhenheit2celcius_arr_fa_V16VOmnisciArrayTyperfRA({ float*, i64, i8 }* nocapture readonly %.1) local_unnamed_addr #0 {
entry:
  %.10.i.i.i = getelementptr { float*, i64, i8 }, { float*, i64, i8 }* %.1, i64 0, i32 1
  %.11.i.i.i = load i64, i64* %.10.i.i.i, align 8, !noalias !1
  %.34.i.i = icmp eq i64 %.11.i.i.i, 0
  br i1 %.34.i.i, label %B14.i.i, label %B26.i.i
B14.i.i:                                          ; preds = %entry
  %.39.i.i = tail call i32 (i8*, ...) @printf(i8* nonnull dereferenceable(1) getelementptr inbounds ([20 x i8], [20 x i8]* @printf_format, i64 0, i64 0), {} undef) #2, !noalias !9
  %.40.i.i = tail call i32 @fflush(i8* null) #2, !noalias !9
  br label %_ZN3rbc5tests12test_omnisci22test_direct_call_array12_3clocals_3e27farhenheit2celcius_arr_2421B40c8tJTC_2fWQA9HW1CcAv0EjzIkAdRoAEtoAgA_3dE63BufferPointer_5bSTRUCT__fPW3WptrLW2WszV5Vbool8W7Wis_nullK_5d_2a.exit
B26.i.i:                                          ; preds = %entry
  %.84.inv.i.i.i = icmp sgt i64 %.11.i.i.i, 0
  br i1 %.84.inv.i.i.i, label %B38.lr.ph.i.i.i, label %B26.endif.endif.endif.i.i
B38.lr.ph.i.i.i:                                  ; preds = %B26.i.i
  %.11.i1.i.i.i = getelementptr { float*, i64, i8 }, { float*, i64, i8 }* %.1, i64 0, i32 0
  %.12.i.i.i.i = load float*, float** %.11.i1.i.i.i, align 8, !noalias !10
  br label %B38.i.i.i
B38.i.i.i:                                        ; preds = %B38.i.i.i, %B38.lr.ph.i.i.i
  %s.2.012.i.i.i = phi double [ 0.000000e+00, %B38.lr.ph.i.i.i ], [ %.191.i.i.i, %B38.i.i.i ]
  %.70.010.i.i.i = phi i64 [ 0, %B38.lr.ph.i.i.i ], [ %.139.i.i.i, %B38.i.i.i ]
  %.139.i.i.i = add nuw nsw i64 %.70.010.i.i.i, 1
  %.13.i.i.i.i = getelementptr float, float* %.12.i.i.i.i, i64 %.70.010.i.i.i
  %.141.i3.i.i.i = load float, float* %.13.i.i.i.i, align 4, !noalias !10
  %.190.i.i.i = fpext float %.141.i3.i.i.i to double
  %.191.i.i.i = fadd double %s.2.012.i.i.i, %.190.i.i.i
  %exitcond.not.i.i.i = icmp eq i64 %.139.i [...]

2022-02-23 19:57 UTC, guilhermeleobas commented
Pamphile, can you disable vectorization and re-run the tests? In Numba this should be possible by defining the following environment variables:
* `NUMBA_LOOP_VECTORIZE=0`
* `NUMBA_SLP_VECTORIZE=0`

**Or** define the `_pass_manager_builder` method in the `JITRemoteCodegen` :

```diff
diff --git a/rbc/irtools.py b/rbc/irtools.py
index f485e65..f83f8cb 100644
--- a/rbc/irtools.py
+++ b/rbc/irtools.py
@@ -88,6 +88,29 @@ class JITRemoteCodeLibrary(codegen.JITCodeLibrary):
 class JITRemoteCodegen(codegen.JITCPUCodegen):
     _library_class = JITRemoteCodeLibrary
 
+    def _pass_manager_builder(self, **kwargs):
+        # copied from
+        # https://github.com/numba/numba/blob/290bcaa63804fb99b1fe238b0f8fe1caf7686899/numba/core/codegen.py#L1240-L1258
+        import llvmlite.llvmpy.passes as lp
+        """
+        Create a PassManagerBuilder.
+
+        Note: a PassManagerBuilder seems good only for one use, so you
+        should call this method each time you want to populate a module
+        or function pass manager.  Otherwise some optimizations will be
+        missed...
+        """
+        opt_level = 2
+        loop_vectorize = 0
+        slp_vectorize = 0
+
+        pmb = lp.create_pass_manager_builder(opt=opt_level,
+                                             loop_vectorize=loop_vectorize,
+                                             slp_vectorize=slp_vectorize,
+                                             **kwargs)
+
+        return pmb
+
     def _get_host_cpu_name(self):
         target_info = TargetInfo()
         return target_info.device_name

```

2022-03-07 19:47 UTC, guilhermeleobas commented
@tupui, I've debug this a while ago, and the failure happens due to a bug in the server. For the input with literal array, the server will randomly crash at `ChunkIter_get_nth` due to `it->skip_size` not being correctly initialized. When the garbage value is `> 0`, the server works as expected, otherwise a segfault is produced. 

```
Thread 11 "omnisci_server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb4ff9700 (LWP 22930)]
bt0x0000555559be0ced in ChunkIter_get_nth (it=0x7fff7c3f8c60, n=0, result=0x7fffb4fed290, is_end=0x7fffb4fed28f) at /home/guilhermeleobas/git/omniscidb-internal/Utils/ChunkIter.cpp:240
240         ArrayOffsetT offset = *(ArrayOffsetT*)current_pos;
(gdb) bt
#0  0x0000555559be0ced in ChunkIter_get_nth (it=0x7fff7c3f8c60, n=0, result=0x7fffb4fed290, is_end=0x7fffb4fed28f) at /home/guilhermeleobas/git/omniscidb-internal/Utils/ChunkIter.cpp:240
#1  0x00005555581ca4ff in array_is_null (chunk_iter_=0x7fff7c3f8c60 "\036", row_pos=0) at /home/guilhermeleobas/git/omniscidb-internal/QueryEngine/ArrayOps.cpp:58
#2  0x00007ffff726a58b in query_group_by_template ()
#3  0x00007ffff726a1ab in multifrag_query_hoisted_literals ()
#4  0x000055555844226f in QueryExecutionContext::launchCpuCode (this=0x7fff7c336300, ra_exe_unit=..., native_code=0x7fff7c513430, hoist_literals=true, literal_buff=..., col_buffers=..., num_rows=...,
    frag_offsets=..., scan_limit=1, error_code=0x7fffb4fedb4c, num_tables=1, join_hash_tables=..., num_rows_to_process=-1)
    at /home/guilhermeleobas/git/omniscidb-internal/QueryEngine/QueryExecutionContext.cpp:646
#5  0x00005555581c824d in Executor::executePlanWithGroupBy (this=0x7fff7c001b30, ra_exe_unit=..., compilation_result=..., hoist_literals=true, results=0x7fff7c4da9f0, device_type=ExecutorDeviceType::CPU,
    col_buffers=..., outer_tab_frag_ids=..., query_exe_context=0x7fff7c336300, num_rows=..., frag_offsets=..., data_mgr=0x55555b41ea90, device_id=0, outer_table_id=-1, scan_limit=1, start_rowid=0,
    num_tables=1, allow_runtime_interrupt=true, render_info=0x0, rows_to_process=-1) at /home/guilhermeleobas/git/omniscidb-internal/QueryEngine/Execute.cpp:3632
#6  0x0000555558272ddf in ExecutionKernel::runImpl (this=0x7fff7c4da990, executor=0x7fff7c001b30, thread_idx=1, shared_context=...)
    at /home/guilhermeleobas/git/omniscidb-internal/QueryEngine/ExecutionKernel.cpp:401
#7  0x0000555558270b41 in ExecutionKernel::run (this=0x7fff7c4da990, executor=0x7fff7c001b30, thread_idx=1, shared_context=...)
...
```

I dump the LLVM IR and what I think it should be a pointer to a ChunkIter struct is actually a `[2 x i64]*` array.

```llvm
; Function Attrs: uwtable
define void @query_group_by_template(i8** nocapture readnone %byte_stream, i8* nocapture readonly %literals, i64* nocapture readnone %row_count_ptr, i64* nocapture readonly %frag_row_off_ptr, i32* %max_matched_ptr, i64* %agg_init_val, i64** %group_by_buffers, i32 %frag_idx, i64* %join_hash_tables, i32* %total_matched, i32* %error_code) #27 {
.entry:
  %0 = getelementptr i8, i8* %literals, i16 0, !ConstantIR.cpp !83
  %1 = bitcast i8* %0 to i32*, !ConstantIR.cpp !83
  %literal_0 = load i32, i32* %1, align 4, !ConstantIR.cpp !83
  %2 = getelementptr i8, i8* %literals, i16 4, !ConstantIR.cpp !83
  %3 = bitcast i8* %2 to i32*, !ConstantIR.cpp !83
  %literal_4 = load i32, i32* %3, align 4, !ConstantIR.cpp !83
  %row_count = load i64, i64* %row_count_ptr, align 8, !NativeCodegen.cpp !18
  %4 = load i32, i32* %max_matched_ptr, align 8, !NativeCodegen.cpp !18
  %crt_matched = alloca i32, align 4, !NativeCodegen.cpp !18
  %old_total_matched = alloca i32, align 4, !NativeCodegen.cpp !18
  %5 = call i32 @pos_start_impl(i32* %error_code), !NativeCodegen.cpp !18
  %6 = call i32 @pos_step_impl(), !NativeCodegen.cpp !18
  %7 = call i32 @group_buff_idx_impl(), !NativeCodegen.cpp !18
  %8 = sext i32 %5 to i64, !NativeCodegen.cpp !18
  %9 = getelementptr i64*, i64** %group_by_buffers, i32 %7, !NativeCodegen.cpp !18
  %col_buffer = load i64*, i64** %9, align 8, !NativeCodegen.cpp !18
  %result_buffer = call i64* @init_shared_mem_nop(i64* %col_buffer, i32 0), !NativeCodegen.cpp !18
  %10 = icmp slt i64 %8, %row_count, !NativeCodegen.cpp !18
  br i1 %10, label %.loop.preheader, label %.exit, !NativeCodegen.cpp !18

.loop.preheader:                                  ; preds = %.entry
  %11 = sext i32 %6 to i64, !NativeCodegen.cpp !18
  br label %.forbody, !NativeCodegen.cpp !18

.forbody:                                         ; preds = %filter_nomatch, %filter_match, %.loop.preheader
  %pos = phi i64 [ %8, %.loop.preheader ], [ %20, %filter_match ], [ %20, %filter_nomatch ], !NativeCodegen.cpp !18
  store i32 0, i32* %crt_matched, align 4, !NativeCodegen.cpp !18
  %12 = call i32 @row_func_hoisted_literals(i64* %result_buffer, i64* null, i32* %crt_matched, i32* %total_matched, i32* %old_total_matched, i32* %max_matched_ptr, i64* %agg_init_val, i64 %pos, i64* %frag_row_off_ptr, i64* %row_count_ptr, i8* %literals, i64* %join_hash_tables, i32 %literal_4, i32 %literal_0), !NativeCodegen.cpp !18
  %13 = and i64 %pos, 63, !NativeCodegen.cpp !84
  %14 = icmp eq i64 %13, 0, !NativeCodegen.cpp !84
  br i1 %14, label %.interrupt_check, label %.error_check, !NativeCodegen.cpp !84

.interrupt_check:                                 ; preds = %.forbody
  %15 = call i1 @check_interrupt(), !NativeCodegen.cpp !84
  %16 = select i1 %15, i32 10, i32 %12, !NativeCodegen.cpp !84
  br label %.error_check, !NativeCodegen.cpp !84

.error_check:                                     ; preds = %.forbody, %.interrupt_check
  %17 = phi i32 [ %16, %.interrupt_check ], [ %12, %.forbody ], !NativeCodegen.cpp !84
  %18 = icmp ne i32 %17, 0, !NativeCodegen.cpp !84
  br i1 %18, label %.error_exit, label %19, !NativeCodegen.cpp !84

.error_exit:                                      ; preds = %.error_check
  call void @record_error_code(i32 %17, i32* %error_code), !NativeCodegen.cpp !84
  ret void, !NativeCodegen.cpp !84

19:                                               ; preds = %.error_check
  %20 = add i64 %pos, %11, !NativeCodegen.cpp !18
  %21 = icmp slt i64 %20, %row_count, !NativeCodegen.cpp !18
  %crt_matched1 = load i32, i32* %crt_matched, align 4, !NativeCodegen.cpp !18
  %22 = icmp ne i32 %crt_matched1, 0, !NativeCodegen.cpp !18
  br i1 %22, label %filter_match, label %filter_nomatch, !NativeCodegen.cpp !18

filter_match:                                     ; preds = %19
  %23 = load i32, i32* %old_total_matched, align 4, !NativeCodegen.cpp !18
  %24 = add i32 %23, %crt_matched1, !NativeCodegen.cpp !18
  %limit_not_reached = icmp slt i32 %24, %4, !NativeCodegen.cpp !18
  %25 = and i1 %21, %limit_not_reached, !NativeCodegen.cpp !18
  br i1 %25, label %.forbody, label %._crit_edge, !NativeCodegen.cpp !18

filter_nomatch:                                   ; preds = %19
  br i1 %21, label %.forbody, label %._crit_edge, !NativeCodegen.cpp !18

._crit_edge:                                      ; preds = %filter_nomatch, %filter_match
  br label %.exit, !NativeCodegen.cpp !18

.exit:                                            ; preds = %._crit_edge, %.entry
  call void @write_back_nop(i64* %col_buffer, i64* %result_buffer, i32 0), !NativeCodegen.cpp !18
  ret void, !NativeCodegen.cpp !18
}

; Function Attrs: alwaysinline
define i32 @row_func_hoisted_literals(i64* %group_by_buff, i64* %varlen_output_buff, i32* %crt_matched, i32* %total_matched, i32* %old_total_matched, i32* %max_matched, i64* %agg_init_val, i64 %pos, i64* %frag_row_off, i64* %num_rows_per_scan, i8* %literals, i64* %join_hash_tables, double %arg_literal_8, double %arg_literal_0) #28 {
entry:
  %0 = call i32 @filter_func_hoisted_literals(i32* %crt_matched, i32* %total_matched, i32* %old_total_matched, i32* %max_matched, i64* %group_by_buff, i64 %pos, double %arg_literal_8, double %arg_literal_0), !NativeCodegen.cpp !18
  ret i32 %0, !NativeCodegen.cpp !85
}

; Function Attrs: alwaysinline
define i32 @filter_func_hoisted_lite [...]

2022-03-08 08:58 UTC, tupui commented
Thanks @guilhermeleobas! Is there anything we can do on our side to go around? Is there an easy fix for the server?

2023-07-13 00:49 UTC, guilhermeleobas commented
Closing in favor of #573

2023-07-13 00:49 UTC, closed without merging