Refactor OmniSci to Heavy
xnd-project/rbc pull request #454
Opened 2022-03-15 13:46 UTC by tupui

Closes #451

2022-03-17 10:18 UTC, pearu requested changes
Thanks, @tupui for this work!

I have a couple of nits.

In addition, at some point, we should filter out heavydb dependent code from test_externals_cmath.py and test_externals_libdevice.py as well and move these under tests/heavyai/

2022-03-17 10:18 UTC, pearu commented on rbc/heavyai/__init__.py
> +import rbc.heavyai.python_operators as operators  # noqa: F401
```suggestion
import .mathimpl as math  # noqa: F401
import .npyimpl as np  # noqa: F401
import .python_operators as operators  # noqa: F401
```

2022-03-17 10:18 UTC, pearu commented on rbc/omniscidb.py
> +msg = "`RemoteOmnisci` is deprecated, use `RemoteHeavyDB` instead."
```suggestion
msg = "`import rbc.omniscidb` is deprecated, use `import rbc.heavyai` instead."
```

2022-03-17 10:18 UTC, pearu commented on rbc/remotejit.py
> +from .heavyai import OmnisciCompilerPipeline
At some point (not necessarily here to keep this PR simple), we'll need to rename `OmnisciCompilerPipeline` as well.

2022-03-17 10:21 UTC, pearu commented
https://github.com/xnd-project/rbc/blob/master/.github/workflows/rbc_test.yml requires an update as well. For instance, currently, CI does not run any of the heavyai tests..

2022-03-18 12:10 UTC, tupui commented
Most tests seem to be passing except: `rbc/tests/heavyai/test_math.py::test_numpy_function[np.positive-cpu]`
There is a core dump when evaluating: `nb.njit(fn)`

2022-03-22 15:15 UTC, tupui commented
ok we debugged with @guilhermeleobas and #445 fixes the segfault.

@pearu Once this is green, I propose to merge maybe with the test skip, and then @guilhermeleobas would remove it in his PR.

2022-03-22 15:35 UTC, tupui commented
> Considering that this PR is mostly about renaming omnisci to heavydb, @tupui , @guilhermeleobas could you explain how #445 that deals with numba internals is related to the changes in this PR?

AFAIU, @guilhermeleobas noticed it elsewhere.

2022-03-22 16:16 UTC, tupui commented
Ok seems like all CI is passing. There is one workflow failing one test but seems unrelated `test_add_ints_rjit`. I tried to relaunch the failed workflow but GitHub is having issues currently.

2022-03-22 16:17 UTC, tupui commented
See here for to view the previous run: https://github.com/xnd-project/rbc/actions/runs/2023309018/attempts/1

2022-03-22 17:44 UTC, tupui commented
@pearu @guilhermeleobas the CI is green. It was just a hiccup (maybe even related to GH's current outage).

2022-03-22 18:33 UTC, guilhermeleobas approved these changes

2022-03-23 08:02 UTC, pearu approved these changes
LGTM! There are a couple of discussion items that should be addressed in a follow-up but let's land this now.

Thanks, @tupui!

2022-03-23 08:04 UTC, tupui commented on .github/workflows/rbc_test.yml
> +          mamba run -n rbc pytest -sv -r A rbc/tests/ -x -k heavyai
Sure 👍

2022-03-23 08:12 UTC, merged