Add support for string proxy methods
xnd-project/rbc pull request #499
Opened 2022-06-14 21:18 UTC by guilhermeleobas

* Add `string_dict_proxy_ method` if the column is a `Column<TextEncodingDict>`.
* Expose the following methods to add and retrieve strings
  * `::getString(string_id)`
  * `::getStringId(string)`
* Enables `nrt` to support unicode strings. From a quick scan of the [`unicode.py`](https://github.com/numba/numba/blob/main/numba/cpython/unicode.py) file, it doesn't seem to require the Python API.

2022-06-15 14:03 UTC, brenocfg requested changes
Suggested a discussion on `StringDictionaryProxy_getString()` that I think we should settle before approving. (The rest LGTM though)

2022-06-15 14:05 UTC, brenocfg commented on rbc/heavydb/column.py
> +    sig = nb_types.voidptr(col_var, row_idx)
Also, shouldn't `col_var` be renamed to `dict_ptr` and `row_idx` to `string_id` or something of that sort? Just to make it clear what these two parameters actually refer to?

2022-06-24 16:24 UTC, brenocfg commented on rbc/heavydb/column.py
> +        cgutils.printf(builder, "%s - %d\n", text.ptr, text.sz)
Leftover print I'm guessing? 😅

2022-06-24 16:29 UTC, guilhermeleobas commented on rbc/heavydb/column.py
> +        cgutils.printf(builder, "%s - %d\n", text.ptr, text.sz)
Yes 😆

2022-07-02 22:10 UTC, guilhermeleobas commented on rbc/heavydb/column_list.py
> +        T = Type.fromnumba(lst.dtype.members[0].dtype.dtype)
Perhaps there's a better way to detect if the columnlist is of type `TextEncodingDict`.

2022-07-08 16:54 UTC, guilhermeleobas commented on rbc/heavydb/column.py
> +            return ('i8* string_dict_proxy_',)
note to myself: check if the heavydb version is >= (6, 2)

2022-07-29 14:09 UTC, pearu approved these changes
LGTM! Thanks, @guilhermeleobas !

2022-07-29 14:26 UTC, merged