Simplify ext_arguments_map ctor
xnd-project/rbc pull request #550
Opened 2023-05-16 04:02 UTC by guilhermeleobas

part of #548

2023-05-16 09:25 UTC, pearu requested changes
Overall looks good! Thanks, @guilhermeleobas!

I have a few suggestions to extend the set of supported types.

2023-05-16 09:25 UTC, pearu commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "bool*",
Also, add `double` and `float`.

2023-05-16 09:25 UTC, pearu commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "Array<double>",
Also add `Array<int8>`, ..., `Array<float32>`, `Array<float32_t>` etc.

2023-05-16 09:25 UTC, pearu commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "Column<double>",
Same: add `Column<int8>`, etc.

2023-05-16 09:25 UTC, pearu commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "ColumnList<int8_t>",
Same: add `ColumnList<int8>`, etc

2023-05-16 09:25 UTC, pearu commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "Column<Array<int8_t>>",
Same as above.

2023-05-16 09:25 UTC, pearu commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "ColumnList<Array<int8_t>>",
Same as above.

2023-05-16 09:25 UTC, pearu commented on rbc/heavydb/remoteheavydb.py
> -                ('double', 'Double'),
I think we'll need these.

2023-05-16 09:25 UTC, pearu commented on rbc/tests/heavydb/test_type_to_extarg.py
> +
I wonder, should we also test the exceptions from user-specified ill-formed types names? For example, when they specify `Array<complex>` in the heavydb signature, will the error message be informative enough for users to not struggle with the unsupported type?

2023-05-16 18:39 UTC, guilhermeleobas commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "bool*",
Done

2023-05-16 18:39 UTC, guilhermeleobas commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "Column<double>",
Done

2023-05-16 18:39 UTC, guilhermeleobas commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "Array<double>",
Done

2023-05-16 18:40 UTC, guilhermeleobas commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "Column<Array<int8_t>>",
Done

2023-05-16 18:40 UTC, guilhermeleobas commented on rbc/tests/heavydb/test_type_to_extarg.py
> +    "ColumnList<Array<int8_t>>",
Done

2023-06-01 10:29 UTC, pearu reviewed
I have two questions. Otherwise looks good to me.

2023-06-01 10:29 UTC, pearu commented on rbc/tests/heavydb/test_column_basic.py
> +@pytest.mark.xfail
Why xfail?

2023-06-01 10:29 UTC, pearu commented on rbc/heavydb/remoteheavydb.py
> -                ('double', 'Double'),
I think we still need these. What do you think?

2023-06-12 13:57 UTC, guilhermeleobas commented
> I think we still need these. What do you think?

Could you think of any example that these types are required?

2023-06-22 11:59 UTC, pearu commented
> > I think we still need these. What do you think?
> 
> Could you think of any example that these types are required?

These are not required per se. I am just thinking about C/C++ users who might write, say, `Array<double>` or `Column<int32_t>`.

Also, these types are included in [test_type_to_extarg.py](https://github.com/xnd-project/rbc/pull/550/files#diff-f614180c1c47fb12101ea9de5d68b9f5070425d5f02a0f050db025f618e2eb20) as primitives.

Another approach is to have a unique list of types that rbc supports and reject all their equivalent variations with an informative exception message such as `"Array<double> is not supported, use Array<float64> instead"`.

2023-06-22 12:59 UTC, guilhermeleobas commented on rbc/heavydb/remoteheavydb.py
> +                ('float64', 'Double'),
Check to see if this part is needed?

2023-06-22 16:09 UTC, merged